###
POST localhost:8080/api/address/create
Content-Type: application/json

{
  "address": "Test Address 1"
}

###
GET localhost:8080/api/address/all

###
GET localhost:8080/api/address/all/0/1

###
GET localhost:8080/api/address/all/1/1

###
PUT localhost:8080/api/address/update/1
Content-Type: application/json

{
    "address": "Test Address Updated"
}

###
PUT localhost:8080/api/address/add/customer/2/1
