###
POST localhost:8080/api/customer/add
Content-type: application/json

{
    "customerName" : "Test Customer",
    "email" : "Test Email",
    "phone" : "Test phone",
    "addresses" : [
        "Test address 1", "Test address 2"
    ]
}

###
GET localhost:8080/api/customer/1

###
GET localhost:8080/api/customer/all
Content-Type: application/json

###
GET localhost:8080/api/customer/all/0/1

###
PUT localhost:8080/api/customer/update/1/name
Content-Type: application/json

{
  "customerName" : "Updated Test Customer"
}

###
PUT localhost:8080/api/customer/update/1/email
Content-Type: application/json

{
  "email" : "Updated Test Email"
}

###
PUT localhost:8080/api/customer/update/1/phone
Content-Type: application/json

{
  "phone" : "Updated Test Phone"
}

###
DELETE localhost:8080/api/customer/delete/1

###
POST localhost:8080/api/customer/2/address/add
Content-Type: application/json

{
  "address" : "Adding New Test Address"
}

###
PUT localhost:8080/api/customer/address/update/3
Content-Type: application/json

{
  "address" : "Updated First Test Address"
}

###
GET localhost:8080/api/customer/1/address/all

###
DELETE localhost:8080/api/customer/1/address/delete/1