###
GET localhost:8080/api/machine/1

###
GET localhost:8080/api/machine/all

###
GET localhost:8080/api/machine/all/0/2

###
POST localhost:8080/api/machine/add
Content-Type: application/json

{
    "machineName" : "Test Machine"
}

###
PUT localhost:8080/api/machine/update/6/name
Content-Type: application/json

{
    "machineName" : "Updated Test Machine"
}

###
DELETE localhost:8080/api/machine/delete/6
