###
GET localhost:8080/api/machine/6

###
GET localhost:8080/api/machine/all

###
POST localhost:8080/api/machine/add
Content-Type: application/json

{
    "machineName" : "Test Machine",
    "machinePrice" : 1000,
    "subassemblies:" : [
        {
            "subassemblyName" : "Test Subassembly",
            "subassemblyPrice" : 100
        }
    ]
}
