###
POST localhost:8080/api/customer/add
Content-type: application/json

{
    "customerName" : "customer",
    "email" : "123@hotmail.com",
    "phone" : 234234,
    "addresses" : [
        "123Lane", "456Street"
    ]
}

###
GET localhost:8080/api/customer/1

###
GET localhost:8080/api/customer/all
Content-Type: application/json

###
POST localhost:8080/api/customer/add/1/address
Content-Type: application/json

{
    "address" : "789Avenue"
}

###
PUT localhost:8080/api/customer/update/1/name
Content-Type: application/json

{
  "customerName" : "newCustomer"
}

###
PUT localhost:8080/api/customer/update/1/email
Content-Type: application/json

{
  "email" : "customer@mail.com"
}

###
PUT localhost:8080/api/customer/update/1/phone
Content-Type: application/json

{
  "phone" : 123123
}

###
DELETE localhost:8080/api/customer/delete/1