###
POST localhost:8080/api/subassembly/add
Content-Type: application/json

{
  "subassemblyName": "Test Subassembly",
  "subassemblyPrice": 100,
  "parts" : [
    {
      "partName": "Test Part for Subassembly",
      "partPrice": 100
    }
  ]
}

###
GET localhost:8080/api/subassembly/21

###
GET localhost:8080/api/subassembly/all
Content-Type: application/json

###
GET localhost:8080/api/subassembly/all/0/1

###
PUT localhost:8080/api/subassembly/update/21
Content-Type: application/json

{
    "subassemblyName": "Updated Subassembly",
    "subassemblyPrice": 100,
    "parts" : [
        {
            "partName": "Test Part for Subassembly",
            "partPrice": 100
        }
    ]
}

###
DELETE localhost:8080/api/subassembly/delete/21